name: CI
on: [push, pull_request,workflow_dispatch]

jobs:
    build:
      name: Run Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: ScriptBuild
          run: ./build.ps1 -Tasks .
          shell: pwsh