name: CI
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
    build:
      name: Run Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: ScriptBuild
          env:
            PAT: ${{ secrets.PAT }}
            COUCOU: ${{ env.COUCOU }}
          run: ./build.ps1 -Tasks . -ResolveDependency
          shell: pwsh